import os
from datetime import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos

# Bundled DejaVu Sans — ships with the repo so rendering is identical locally
# and on the deployed (Linux) HF Space, and covers the accented characters and
# typographic punctuation that Claude's generated text and place names use.
_FONT_DIR = os.path.join(os.path.dirname(__file__), "fonts")
_FONTS = {
    "":   os.path.join(_FONT_DIR, "DejaVuSans.ttf"),
    "B":  os.path.join(_FONT_DIR, "DejaVuSans-Bold.ttf"),
    "I":  os.path.join(_FONT_DIR, "DejaVuSans-Oblique.ttf"),
    "BI": os.path.join(_FONT_DIR, "DejaVuSans-BoldOblique.ttf"),
}
_USE_TTF = all(os.path.exists(p) for p in _FONTS.values())

# Characters fpdf2's core (non-Unicode) fonts can't encode, mapped to ASCII
# equivalents. Applied as a belt-and-suspenders pass even with a Unicode font,
# since it also normalizes typography for a plainer, more consistent look.
_PDF_CHAR_MAP = {
    "‘": "'", "’": "'",   # ‘ ’
    "“": '"', "”": '"',  # “ ”
    "–": "-", "—": "-",  # – —
    "…": "...",               # …
    " ": " ",                 # non-breaking space
}


def sanitize_for_pdf(text) -> str:
    """Replace smart quotes/dashes/ellipsis with ASCII equivalents before writing to the PDF."""
    if text is None:
        return ""
    text = str(text)
    for char, replacement in _PDF_CHAR_MAP.items():
        text = text.replace(char, replacement)
    return text

_BLUE   = (20, 60, 140)
_DARK   = (30, 30, 30)
_GREY   = (90, 90, 90)
_SILVER = (150, 150, 150)
_FILL   = (240, 245, 255)


# ── Terminal renderer ────────────────────────────────────────────────────────

def render_terminal(itinerary: dict) -> None:
    dest = itinerary.get("destination", "Your Trip")
    w = 70
    print()
    print("=" * w)
    print(f"TripMind — {dest}".center(w))
    print("=" * w)

    def section(title: str) -> None:
        print(f"\n── {title} " + "─" * max(0, 60 - len(title)))

    section("DESTINATION OVERVIEW")
    print(itinerary.get("overview", ""))

    section("WHERE TO STAY")
    for h in itinerary.get("hotels", []):
        print(f"  {h['name']}  |  {h['neighborhood']}  |  {h['price_range']}")
        print(f"    {h['why']}")
        print()

    section("WHERE TO EAT")
    for r in itinerary.get("restaurants", []):
        print(f"  {r['name']}  |  {r['cuisine']}  |  {r['price_range']}")
        print(f"    {r['why']}")
        print()

    section("WHAT TO DO")
    for a in itinerary.get("activities", []):
        print(f"  {a['name']}  ({a['category']})")
        print(f"    {a['why']}")
        print(f"    Tip: {a['tip']}")
        print()

    section("PRACTICAL TIPS")
    for tip in itinerary.get("practical_tips", []):
        print(f"  • {tip}")
    print()


# ── PDF renderer ─────────────────────────────────────────────────────────────

class _TripPDF(FPDF):
    def __init__(self, font_name: str):
        super().__init__()
        self.font_name = font_name

    def footer(self):
        self.set_y(-14)
        self.set_font(self.font_name, "I", 8)
        self.set_text_color(*_SILVER)
        self.cell(0, 6, f"Page {self.page_no()}  —  Generated by TripMind",
                  align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def section_header(self, title: str) -> None:
        self.set_font(self.font_name, "B", 11)
        self.set_fill_color(*_FILL)
        self.set_text_color(*_BLUE)
        self.cell(0, 8, f"  {sanitize_for_pdf(title)}", fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(*_DARK)
        self.ln(3)

    def place_heading(self, name: str, detail: str, price: str = "") -> None:
        self.set_font(self.font_name, "B", 10)
        self.set_text_color(*_DARK)
        label = f"{sanitize_for_pdf(name)}  |  {sanitize_for_pdf(detail)}"
        if price:
            label += f"  |  {sanitize_for_pdf(price)}"
        self.multi_cell(0, 6, label)
        self.ln(1)

    def body_text(self, text: str) -> None:
        self.set_font(self.font_name, "", 10)
        self.set_text_color(*_GREY)
        self.multi_cell(0, 5, sanitize_for_pdf(text))
        self.ln(3)

    def tip_text(self, text: str) -> None:
        self.set_font(self.font_name, "I", 9)
        self.set_text_color(*_SILVER)
        self.multi_cell(0, 5, f"Tip: {sanitize_for_pdf(text)}")
        self.ln(3)


def render_pdf(itinerary: dict, filename: str | None = None) -> str:
    if filename is None:
        dest_slug = itinerary.get("destination", "itinerary").lower().replace(" ", "_")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        os.makedirs("itineraries", exist_ok=True)
        filename = f"itineraries/{dest_slug}_{timestamp}.pdf"

    font = "DejaVuSans" if _USE_TTF else "Helvetica"
    pdf = _TripPDF(font)

    if _USE_TTF:
        for style, path in _FONTS.items():
            pdf.add_font("DejaVuSans", style=style, fname=path)

    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    dest = sanitize_for_pdf(itinerary.get("destination", "Your Trip"))

    # Title block
    pdf.set_font(font, "B", 22)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 12, sanitize_for_pdf(f"TripMind — {dest}"),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font(font, "I", 9)
    pdf.set_text_color(*_SILVER)
    pdf.cell(0, 5, "Your personalised travel itinerary",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    # Overview
    pdf.section_header("DESTINATION OVERVIEW")
    pdf.body_text(itinerary.get("overview", ""))
    pdf.ln(2)

    # Hotels
    pdf.section_header("WHERE TO STAY")
    for h in itinerary.get("hotels", []):
        pdf.place_heading(h["name"], h["neighborhood"], h["price_range"])
        pdf.body_text(h["why"])

    # Restaurants
    pdf.section_header("WHERE TO EAT")
    for r in itinerary.get("restaurants", []):
        pdf.place_heading(r["name"], r["cuisine"], r["price_range"])
        pdf.body_text(r["why"])

    # Activities
    pdf.section_header("WHAT TO DO")
    for a in itinerary.get("activities", []):
        pdf.place_heading(a["name"], a["category"])
        pdf.body_text(a["why"])
        pdf.tip_text(a["tip"])

    # Practical tips
    pdf.section_header("PRACTICAL TIPS")
    for tip in itinerary.get("practical_tips", []):
        pdf.set_font(font, "", 10)
        pdf.set_text_color(*_DARK)
        pdf.multi_cell(0, 6, sanitize_for_pdf(f"•  {tip}"))
        pdf.ln(1)

    pdf.output(filename)
    print(f"\nPDF saved to {filename}")
    return filename


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    sample = {
        "destination": "Paris",
        "overview": (
            "Paris is the city of light, where grand boulevards and hidden courtyards "
            "coexist in perfect tension. September brings golden light, smaller crowds, "
            "and the kind of unhurried pace that lets a couple linger over a second café "
            "crème without guilt."
        ),
        "hotels": [
            {"name": "Hôtel Le Marais Bastille", "neighborhood": "Le Marais", "price_range": "$$",
             "why": "Central location puts you within walking distance of the Picasso Museum and weekend markets."},
            {"name": "Le Petit Moulin", "neighborhood": "Saint-Germain", "price_range": "$$$",
             "why": "Boutique hotel in a converted bakery — quiet street, romantic atmosphere ideal for couples."},
            {"name": "Generator Paris", "neighborhood": "Oberkampf", "price_range": "$",
             "why": "Stylish mid-range option with a rooftop bar, great for travellers who want to explore at night."},
        ],
        "restaurants": [
            {"name": "Bistrot Paul Bert", "cuisine": "Classic French", "price_range": "$$",
             "why": "Old-school Paris bistro with legendary steak frites — exactly what a relaxed couple's evening calls for."},
            {"name": "Du Pain et des Idées", "cuisine": "Bakery / Pastries", "price_range": "$",
             "why": "Possibly the best croissants in Paris; matches your pastry preference perfectly."},
            {"name": "Septime", "cuisine": "Modern French", "price_range": "$$$",
             "why": "Market-driven tasting menu, perfect for a special dinner — book well ahead."},
            {"name": "L'As du Fallafel", "cuisine": "Middle Eastern", "price_range": "$",
             "why": "A Marais institution. Quick, cheap, outstanding — great for a casual lunch between museums."},
        ],
        "activities": [
            {"name": "Musée d'Orsay", "category": "Museum",
             "why": "World-class Impressionist collection; relaxed pace lets you take your time without rush.",
             "tip": "Book timed entry online to skip the queue — arrive 10 min early."},
            {"name": "Centre Pompidou", "category": "Museum",
             "why": "Matches your art interest with modern and contemporary work; rooftop view is a bonus.",
             "tip": "Last entry is 90 min before closing."},
            {"name": "Jardin du Luxembourg", "category": "Park",
             "why": "Perfect for a slow morning walk between museums — benches, fountains, no admission.",
             "tip": "Grab pastries from a nearby boulangerie first."},
            {"name": "Sainte-Chapelle", "category": "Landmark",
             "why": "The stained glass is jaw-dropping and less crowded than Notre-Dame — suits a relaxed itinerary.",
             "tip": "Go on a sunny morning when the light comes through the windows."},
            {"name": "Père Lachaise Cemetery", "category": "Landmark",
             "why": "A surprisingly beautiful afternoon walk; peaceful, historic, deeply Parisian.",
             "tip": "Pick up the free map at the entrance — easy to get lost without it."},
        ],
        "practical_tips": [
            "Transport: A carnet of 10 metro tickets is the most economical option for 5 days.",
            "Customs: Greet shopkeepers and waiters with 'Bonjour' — it matters more than you'd expect.",
            "Best time: September mornings are cool; bring a light jacket for evenings.",
            "Watch-out: Many smaller restaurants close between 2:30–7pm — plan lunch before 2pm.",
        ],
    }

    print("=== Terminal render ===")
    render_terminal(sample)

    print("=== PDF render ===")
    render_pdf(sample, "sample_itinerary.pdf")
